"""Developer and content kits: validate 25-kits/ and render them (the fields and rules: step 7 of _system/PLAYBOOK.md).

Source of truth (edit these):   25-kits/dev-requirements.yaml, 25-kits/snippets/<key>.md, 25-kits/content.yaml,
                                25-kits/differences.yaml (optional: the differences ledger)
Generated (never edit by hand): 60-outputs/dev/, 60-outputs/content/, 60-outputs/agent-pack/dev-requirements.json,
                                60-outputs/agent-pack/content-library.json; the ledgers of knowledge graph phase 3 (ledgers(),
                                ledger_pages()): 50-maps/numbers.md, 50-maps/differences.md, 60-outputs/dev/differences.md,
                                60-outputs/content/questions.md and questions.json, and the agent pack's numbers.json,
                                differences.json and question-bank.json
Called only by _system/build_kb.py, which passes itself as `bk` (YAML loader, Markdown escaping, excluded photos):
validate() runs inside its validate-before-write pass, build() after the agent pack is written. No clock, no network.
A kit names a speaker only where the claim's `who` holds that person's name and sessions.yaml does not mark it inferred;
everything else is credited to "Google at <event> (Day N)", "a community speaker", or "a speaker" where nothing recorded says
which (the owner's rule: no proof, no name). An angle point that mixes documented and undocumented event claims is "Partly documented".
Every kit item is also a node of the agent pack's graph (kit_items(): req:DEV-SRV-01, fact:F-012, ..., term:<slug>) with `topics`
derived from its claims; build_kb.py turns these into `used_by` on claims, the topic pages' kit items, graph.json and links.json.
Things (knowledge graph phase 1): build_kb.py matches 20-claims/entities.yaml against the claims and passes kb['item_entities']; build() writes
them as `entities` on every kit item ([{id, count, own}]; item_texts() gives the item's own words), `defines` on glossary terms and an
`entities` column in requirements.csv.
The community edition (kb['edition'], set by build_kb.py from _system/edition.yaml): 25-kits/content.yaml holds every wording rule and
glossary term and a short preview of the media kit. build() then writes 60-outputs/content/ as README.md (the preview, and how to reach
the author), glossary.md and content-library.json (with "edition": "community" and a note); it does not write the fact sheet, myths, story
angles, quotes, the question bank (questions.md, questions.json, question-bank.json) or the numbers registry (50-maps/numbers.md, removed
when present, and numbers.json). The developer kit and the differences ledger are the same in both editions.
The community kit says so itself: its content.yaml carries `edition: community` (the full kit has no such key, or `edition: full`), and
validate() stops the build when the kit and _system/edition.yaml disagree, so a checkout that lost edition.yaml or edition.py never makes
the full edition's pages from the preview, and the community edition is never made from the full kit.
"""
import csv, io, json, re
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict

KITS = '25-kits'
GEN = '<!-- GENERATED by _system/kits.py from 25-kits/. Do not edit; change 25-kits/ and rebuild. -->'
LEVELS = {'MUST': 'Required: the site is not ready to launch without it.',
          'SHOULD': 'Recommended: skip it only for a reason you can name.',
          'MAY': 'Optional: worth doing where it fits.',
          'AVOID': 'Must not: the site is not ready to launch while it does this.'}
STATUS = {'documented': ('Documented', 'At least one cited Google document states or supports it.'),
          'event-only': ('Said at Search Central Live', "Said or shown at the event and not in Google's documentation. "
                         'Present it as said at Search Central Live, never as documented policy.')}
GRADES = dict(STATUS, mixed=('Partly documented', "Some of its claims are in Google's documentation and some were only said or shown at the event: "
                                'check each claim and present the undocumented part as said at Search Central Live.'),
              press=('Reported by the press', 'A third-party report of what Google said, not Google\'s documentation.'),
              analysis=("Author's analysis", "The author's interpretation. Never attribute it to Google."))
USES = {'stat': 'Stats', 'headline': 'Headlines', 'context': 'Context'}
FORMATS = {'linkedin': 'LinkedIn post', 'article': 'Article', 'newsletter': 'Newsletter', 'video': 'Video', 'carousel': 'Carousel', 'talk': 'Talk',
           'podcast': 'Podcast', 'infographic': 'Infographic'}
SAID = 'said at Search Central Live'
EVENT = ('slide', 'stage')
SAYS = {'slide': 'Shown on a slide', 'stage': 'Said on stage', 'docs': "Google's documentation", 'press': 'Press report', 'analysis': "Author's analysis"}
DEV_KEYS, AREA_KEYS = ('areas',), ('id', 'title', 'intro', 'requirements')
REQ_KEYS = ('id', 'level', 'title', 'why', 'how', 'test', 'snippet', 'claims', 'docs', 'status')
CONTENT_KEYS = ('wording_rules', 'facts', 'myths', 'quotes', 'angles', 'glossary')
KIT_EDITIONS = ('full', 'community')  # content.yaml's optional `edition`: the community kit says community (see validate())
ITEM_KEYS = {'facts': ('id', 'statement', 'claims', 'status', 'use'), 'myths': ('id', 'myth', 'fact', 'claims', 'status'), 'quotes': ('id', 'claim'),
             'angles': ('id', 'title', 'audience', 'formats', 'hook', 'points', 'caution', 'cta'), 'glossary': ('term', 'definition', 'claims')}
ITEM_ID = {'facts': 'F', 'myths': 'M', 'quotes': 'Q', 'angles': 'A'}
REQ_ID = re.compile(r'DEV-([A-Z]{2,6})-\d{2}')
CID_FULL = re.compile(r'D\d+-C\d{3}')
FENCE = re.compile(r'(`{3,}|~{3,})[ \t]*([^\s`]*)[ \t]*')
GENERIC = re.compile(r'\b(google|community|speakers?|panel|audience|unknown)\b', re.I)  # 'Google', 'a community speaker': not a person
DIFF_FILE = 'differences.yaml'  # optional: the differences ledger (event against documentation)
DIFF_KEYS = ('id', 'title', 'event', 'docs', 'pages', 'analysis', 'follow')
DIFF_ID = re.compile(r'DIF-\d{2}')
LDJSON = re.compile(r'<script[^>]*type\s*=\s*["\']application/ld\+json["\'][^>]*>(.*?)</script>', re.I | re.S)
# The community edition (kb['edition'], from _system/edition.yaml): content.yaml holds the wording rules, the glossary and a short
# preview of the media kit; content-library.json says so with these two keys, which the full edition's file does not have.
COMMUNITY_NOTE = ('Community edition: the wording rules and the glossary are complete; the facts, myths, story angles and quotes are a short '
                  'preview of the full media kit, which is not part of this edition.')
WORDS = ('no', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten')


def link_text(s, bk):  # Markdown link text: brackets escaped, so a placeholder like "[Company name]" shows as written
    return bk.md(s).replace('[', '\\[').replace(']', '\\]')


# ---------------------------------------------------------------- who said it
def speakers(s):
    return [x for x in (s.get('speaker') if isinstance(s.get('speaker'), list) else [s.get('speaker')]) if isinstance(x, str) and x.strip()]


def person(x):
    return isinstance(x, str) and x[:1].isupper() and not GENERIC.search(x)


def people(S):
    """Person names that speak in the sessions, and the Googlers among them (they speak outside lightning and poster slots)."""
    names = {x for s in S.values() for x in speakers(s) if person(x)}
    google = {x for s in S.values() if s.get('kind', 'talk') not in ('lightning', 'poster') for x in speakers(s) if person(x)}
    return names, google


def inferred(name, s):
    t = f"{s.get('role') or ''} {s.get('note') or ''}"
    return 'speaker inferred' in t.lower() or re.search(re.escape(name) + r"[^.;]*\binferred\b", t, re.I) is not None


def proven(c, S):
    """The claim's speaker when it is proven: a person's name in `who` that sessions.yaml does not mark as inferred."""
    if c.get('label') not in EVENT or c.get('s') not in S: return None
    w = c.get('who')
    return w if person(w) and not inferred(w, S[c['s']]) else None


def who_short(c, S, google, sources):
    """Google, a community speaker, or 'a speaker' when nothing recorded says which (a D<day>-S00 point, or a lightning slot with a Google host)."""
    if c['label'] == 'analysis': return 'the author'
    if c['label'] in ('docs', 'press'): return ', '.join(dict.fromkeys(sources[k]['publisher'] for k in c.get('src', []) if k in sources))
    s, w = S[c['s']], c.get('who')
    if w == 'audience': return 'an audience member'
    if isinstance(w, str) and w != 'unknown' and not person(w):  # who: Google, a community speaker
        return 'Google' if 'google' in w.lower() else 'a community speaker' if 'community' in w.lower() else 'a speaker'
    if s.get('kind', 'talk') in ('lightning', 'poster'):
        if person(w): return 'Google' if w in google else 'a community speaker'
        return 'a speaker' if any(x in google or 'google' in x.lower() for x in speakers(s)) else 'a community speaker'
    if not speakers(s): return 'Google' if person(w) and w in google else 'a speaker'  # D<day>-S00: no speaker list to go by
    return 'Google'


def documented(c):
    return c.get('ver') in ('confirmed', 'consistent') or c.get('label') == 'docs'


def grade(cs):
    if any(documented(c) for c in cs): return 'documented'
    if any(c.get('label') in EVENT for c in cs): return 'event-only'
    return 'press' if any(c.get('label') == 'press' for c in cs) else 'analysis'


def grade_point(cs):
    """An angle point: 'mixed' when it rests on documented claims and on event claims the documentation does not back."""
    g = grade(cs)
    return 'mixed' if g == 'documented' and any(c.get('label') in EVENT and not documented(c) and c.get('who') != 'audience' for c in cs) else g


# ---------------------------------------------------------------- links: what rests on a claim (knowledge graph, phase 0)
# Every kit item is a node of the agent pack's graph.json and links.json: <prefix>:<key>, e.g. req:DEV-SRV-01, fact:F-012,
# term:crawl-budget (a glossary term's key is the term made a slug by build_kb.node_slug). Lists of items follow KIND_ORDER, then key.
KIND_ORDER = ('requirement', 'fact', 'myth', 'quote', 'angle', 'term')
PREFIX = {'requirement': 'req', 'fact': 'fact', 'myth': 'myth', 'quote': 'quote', 'angle': 'angle', 'term': 'term'}
KIT_FILE = {k: 'dev-requirements.json' if k == 'requirement' else 'content-library.json' for k in KIND_ORDER}


def quote_text(c, bk):
    return bk.nt(c.get('quote') or '').strip('"').strip('“”')


def item_claims(part, x):
    """The claim ids a kit item rests on, each once, in the order the kit lists them (an angle: every point's claims)."""
    if part == 'quotes': return [x['claim']]
    if part == 'angles': return list(dict.fromkeys(c for p in x['points'] for c in p['claims']))
    return list(dict.fromkeys(x['claims']))


def term_aliases(term, bk):
    """The spellings a glossary term is found by: the term itself; the part before a parenthesis and the part inside it (unless
    that is a list with commas): 'Crawl rate limit (hostload)'; and each part of 'A and B' or 'A, B and C': 'BERT, RankBrain and
    MUM'. Original spellings, first seen first, one per normalised key (build_kb.norm_key), each at least two characters long."""
    t = bk.nt(term)
    out = [t]
    m = re.fullmatch(r'(.+?)\s*\(([^()]+)\)', t)
    base = m[1] if m else t
    if m: out += [base] + ([m[2].strip()] if ',' not in m[2] else [])
    if re.search(r'\sand\s', base): out += [p.strip() for p in re.split(r',\s*|\s+and\s+', base)]
    keep, seen = [], set()
    for a in out:
        k = bk.norm_key(a)
        if len(k) >= 2 and k not in seen: seen.add(k); keep.append(a)
    return keep


def kit_items(kb, bk):
    """Every kit item as {node id: {kind, key, name, claims, topics, file[, aliases]}}, in KIND_ORDER then key. claims: the public
    claim ids it rests on; topics: the topic ids of those claims, most frequent first, ties in topics.yaml order. Computed once per
    build and kept in kb['kit_items']; build_kb.py uses it for used_by, topic pages, links.json and graph.json."""
    if 'kit_items' in kb: return kb['kit_items']
    kit, CL = kb['kits'], {c['id']: c for c in kb['claims'] if c.get('private') is not True}
    rank = {t: i for i, t in enumerate(kb['topics'])}
    ct = kit['content']
    raw = [('requirement', r['id'], r['title'], item_claims('requirements', r)) for a in kit['areas'] for r in a['requirements']]
    raw += [('fact', x['id'], x['statement'], item_claims('facts', x)) for x in ct['facts']]
    raw += [('myth', x['id'], x['myth'], item_claims('myths', x)) for x in ct['myths']]
    raw += [('quote', x['id'], quote_text(CL[x['claim']], bk), item_claims('quotes', x)) for x in ct['quotes']]
    raw += [('angle', x['id'], x['title'], item_claims('angles', x)) for x in ct['angles']]
    raw += [('term', bk.node_slug(x['term']), x['term'], item_claims('glossary', x)) for x in ct['glossary']]
    out = {}
    for kind, key, name, cids in sorted(raw, key=lambda r: (KIND_ORDER.index(r[0]), r[1])):
        n = Counter(t for x in cids for t in CL[x]['topics'])
        rec = {'kind': kind, 'key': key, 'name': bk.nt(name), 'claims': cids, 'topics': sorted(n, key=lambda t: (-n[t], rank[t])), 'file': KIT_FILE[kind]}
        if kind == 'term': rec['aliases'] = term_aliases(name, bk)
        out[f'{PREFIX[kind]}:{key}'] = rec
    kb['kit_items'] = out
    return out


def item_texts(kb, bk):
    """Each kit item's own words, one line, by node id: what build_kb.py matches the things against besides the item's claims. A
    requirement: title and why; a fact: the statement; a myth: the myth and its fact; a quote: the quotation; an angle: title, hook and
    points; a glossary term: the term and its definition. Parts are joined with ' · ' so no alias can run across two of them."""
    kit, CL = kb['kits'], {c['id']: c for c in kb['claims'] if c.get('private') is not True}
    ct, j = kit['content'], lambda *p: ' · '.join(bk.nt(x) for x in p)
    out = {f"req:{r['id']}": j(r['title'], r['why']) for a in kit['areas'] for r in a['requirements']}
    out.update({f"fact:{x['id']}": j(x['statement']) for x in ct['facts']})
    out.update({f"myth:{x['id']}": j(x['myth'], x['fact']) for x in ct['myths']})
    out.update({f"quote:{x['id']}": quote_text(CL[x['claim']], bk) for x in ct['quotes']})
    out.update({f"angle:{x['id']}": j(x['title'], x['hook'], *[p['text'] for p in x['points']]) for x in ct['angles']})
    out.update({f"term:{bk.node_slug(x['term'])}": j(x['term'], x['definition']) for x in ct['glossary']})
    return out


# ---------------------------------------------------------------- snippets
def parse_snippet(text, where, E, W):
    """A title line, a few sentences, and one or more fenced code blocks (prose between blocks becomes that block's note)."""
    title, prose, blocks, cur = None, [], [], None
    for ln in text.replace('\r\n', '\n').split('\n'):
        if cur is not None:
            if re.fullmatch(re.escape(cur['fence'][0]) + '{%d,}[ \t]*' % len(cur['fence']), ln.strip()): blocks.append(cur); cur = None
            else: cur['lines'].append(ln)
            continue
        m = FENCE.fullmatch(ln.strip()) if ln.lstrip().startswith(('```', '~~~')) else None
        if m: cur, prose = {'fence': m[1], 'lang': m[2], 'lines': [], 'note': ' '.join(prose)}, []; continue
        if not ln.strip(): continue
        if title is None: title = ln.strip().lstrip('#').strip(); continue
        prose.append(ln.strip())
    if cur is not None: E.append(f'{where}: the code block opened with {cur["fence"]} is never closed')
    if not title: E.append(f'{where}: the first line must be a short title'); title = ''
    if not blocks and cur is None: E.append(f'{where}: no fenced code block (```html ... ```)')
    text0 = blocks[0]['note'] if blocks else ' '.join(prose)
    if blocks: blocks[0]['note'] = ''
    if prose and blocks: W.append(f'{where}: text after the last code block is left out; put it before the code')
    if not text0: W.append(f'{where}: add one to three sentences between the title and the code')
    out = []
    for i, b in enumerate(blocks, 1):
        code = '\n'.join(b['lines']).strip('\n')
        lang = b['lang'].lower()
        tag = f'{where} code block {i}'
        if not code.strip(): E.append(f'{tag}: empty'); continue
        if not lang: W.append(f'{tag}: no language after the fence (```html, ```json, ```xml, ```http ...)')
        try:
            if lang in ('json', 'jsonld', 'json-ld'): json.loads(code)
            elif lang == 'xml' or lang.endswith('sitemap'): ET.fromstring(code.encode('utf-8'))
            if lang in ('html', 'htm', 'xhtml'):
                for j in LDJSON.findall(code): json.loads(j)
        except json.JSONDecodeError as x: E.append(f'{tag}: the JSON is not valid ({x})')
        except ET.ParseError as x: E.append(f'{tag}: the XML is not well-formed ({x})')
        out.append({'lang': lang, 'code': code, 'note': b['note']})
    return {'title': title, 'text': text0, 'code': out}


# ---------------------------------------------------------------- validation (nothing is written here)
def validate(root, kb, E, W, bk):
    """Check 25-kits/ against the claims, sources and sessions in kb; store the parsed kits in kb['kits']."""
    K = root / KITS
    claims = kb.get('claims') or []
    by_id = {c['id']: c for c in claims if isinstance(c, dict) and isinstance(c.get('id'), str)}
    public = {i for i, c in by_id.items() if c.get('private') is not True}
    sources, S = kb.get('sources') or {}, kb.get('sessions') or {}
    names, google = people(S)
    names |= {c['who'] for c in by_id.values() if person(c.get('who'))}
    n0 = len(E)
    dev, content, snippets = bk.read_yaml(K / 'dev-requirements.yaml', E), bk.read_yaml(K / 'content.yaml', E), {}
    for p in sorted((K / 'snippets').glob('*')) if (K / 'snippets').is_dir() else []:
        where = f'{KITS}/snippets/{p.name}'
        if p.suffix != '.md' or not p.is_file(): E.append(f'{where}: only <key>.md files belong in {KITS}/snippets/'); continue
        if not bk.KEBAB.fullmatch(p.stem): E.append(f'{where}: the file name must be a lowercase kebab-case key, e.g. canonical-link.md'); continue
        try: txt = p.read_text(encoding='utf-8')
        except UnicodeDecodeError: E.append(f'{where}: not UTF-8 text; save it as UTF-8'); continue
        snippets[p.stem] = dict(parse_snippet(txt, where, E, W), key=p.stem, raw=txt)
    if len(E) > n0: return

    def rec(x, where, keys, optional=()):
        if not isinstance(x, dict): E.append(f'{where}: must be a mapping'); return False
        for k in x:
            if k not in keys: E.append(f'{where}: unknown key "{k}"{bk.hint(k, keys)}')
        for k in keys:
            if k not in x and k not in optional: E.append(f'{where}: missing key "{k}"')
        return True

    def text(x, k, where, multi=False):
        v = x.get(k)
        if k not in x: return ''
        if not isinstance(v, str) or not v.strip(): E.append(f'{where}: {k} must be a non-empty string'); return ''
        if not multi and '\n' in v.strip(): W.append(f'{where}: {k} spans several lines; outputs join it into one')
        return v

    def cited(v, where, key='claims'):
        if not isinstance(v, list) or any(not isinstance(x, str) for x in v): E.append(f'{where}: {key} must be a list of claim ids, e.g. [D1-C001]'); return []
        if not v: E.append(f'{where}: {key} is empty; cite at least one public claim')
        bk.dups(v, f'{where}: {key}', E)
        for x in v:
            if not CID_FULL.fullmatch(x): E.append(f'{where}: {key} must list claim ids like D1-C001, found {x!r}')
            elif x not in by_id: E.append(f'{where}: cites {x}, which does not exist')
            elif x not in public: E.append(f'{where}: cites {x}, which is private')
        return [by_id[x] for x in v if x in public]

    def free(where, obj, cs):
        """Claim ids written in the text exist and are public, no excluded photo, and a person is named only on proof."""
        blob = json.dumps(obj, ensure_ascii=False, default=str)
        for x in bk.cited_ids(blob, where, E):
            if x not in by_id: E.append(f'{where}: mentions {x}, which does not exist')
            elif x not in public: E.append(f'{where}: mentions {x}, which is private')
        for x in bk.excluded_in(obj): E.append(f'{where}: names {x}, which must never appear in a shared output')
        if cs and re.search(r'community speaker', blob, re.I) and not any(c.get('label') in EVENT and who_short(c, S, google, sources) == 'a community speaker' for c in cs):
            E.append(f'{where}: says "community speaker", but none of its claims is a slide or stage claim credited to a community speaker; credit the speaker its claims name')
        ok = {proven(c, S) for c in cs}
        for n in sorted(names):
            if re.search(r'(?<!\w)' + re.escape(n) + r'(?!\w)', blob) and n not in ok:
                E.append(f'{where}: names {n}, but none of its claims is proven to be {n}\'s (who: {n}, not marked inferred in sessions.yaml); '
                         'leave the name out and credit "Google" or "a community speaker"')

    def status(st, where, cs):
        if not isinstance(st, str) or st not in STATUS: E.append(f'{where}: status must be documented or event-only, found {st!r}'); return
        if st == 'documented' and grade(cs) != 'documented' and cs:
            E.append(f'{where}: status documented, but none of its claims is confirmed, consistent or a docs claim; use event-only or cite the documentation')
        if st == 'event-only' and cs and not any(c.get('label') in EVENT for c in cs):
            E.append(f'{where}: status event-only needs at least one slide or stage claim')

    # ---- dev-requirements.yaml
    areas, req_ids, area_ids, used, codes = [], Counter(), Counter(), Counter(), {}
    if not isinstance(dev, dict) or not isinstance(dev.get('areas'), list): E.append(f'{KITS}/dev-requirements.yaml: needs areas: [...]'); dev = {'areas': []}
    for k in dev:
        if k not in DEV_KEYS: E.append(f'{KITS}/dev-requirements.yaml: unknown top-level key "{k}"{bk.hint(k, DEV_KEYS)}')
    for a in dev['areas']:
        aid = a.get('id') if isinstance(a, dict) else None
        wa = f'dev area {aid}'
        if not rec(a, wa, AREA_KEYS): continue
        if not isinstance(aid, str) or not bk.KEBAB.fullmatch(aid): E.append(f'{wa}: id must be lowercase kebab-case, e.g. status-codes')
        area_ids[str(aid)] += 1
        for k in ('title', 'intro'): text(a, k, wa, multi=k == 'intro')
        free(wa, {k: v for k, v in a.items() if k != 'requirements'}, [])
        reqs = a.get('requirements')
        if not isinstance(reqs, list) or not reqs: E.append(f'{wa}: requirements must be a non-empty list'); reqs = []
        good = []
        for r in reqs:
            rid = r.get('id') if isinstance(r, dict) else None
            wr = f'requirement {rid}'
            if not rec(r, wr, REQ_KEYS, optional=('snippet', 'docs')): continue
            m = REQ_ID.fullmatch(rid) if isinstance(rid, str) else None
            if not m: E.append(f'{wr}: id must look like DEV-REN-01 (DEV-, an area code in capitals, -, two digits)')
            else: codes.setdefault(m[1], set()).add(str(aid))
            req_ids[str(rid)] += 1
            if not isinstance(r.get('level'), str) or r['level'] not in LEVELS: E.append(f'{wr}: level must be one of {", ".join(LEVELS)}, found {r.get("level")!r}')
            for k in ('title', 'why', 'how', 'test'): text(r, k, wr, multi=k in ('why', 'how', 'test'))
            cs = cited(r.get('claims'), wr)
            docs = r.get('docs') or []
            if not isinstance(docs, list) or any(not isinstance(x, str) for x in docs): E.append(f'{wr}: docs must be a list of source keys, e.g. [robots-spec]'); docs = []
            bk.dups(docs, f'{wr}: docs', E)
            for k in docs:
                if k not in sources: E.append(f'{wr}: unknown docs key {k} (add it to 20-claims/sources.yaml first)')
                elif (sources[k].get('kind') or 'google') != 'google': E.append(f'{wr}: docs key {k} is a press source; docs lists Google pages only')
            st = r.get('status')
            if not isinstance(st, str) or st not in STATUS: E.append(f'{wr}: status must be documented or event-only, found {st!r}')
            elif st == 'documented' and not docs: E.append(f'{wr}: status documented needs at least one Google page in docs')
            elif st == 'event-only':
                if isinstance(r.get('why'), str) and SAID.lower() not in r['why'].lower(): E.append(f'{wr}: event-only: write "{SAID}" in why')
                if cs and not any(c.get('label') in EVENT for c in cs): E.append(f'{wr}: status event-only needs at least one slide or stage claim')
                if grade(cs) == 'documented': W.append(f'{wr}: event-only, but it cites documented claims; consider status documented with the page in docs')
            sn = r.get('snippet')
            if sn is not None:
                if not isinstance(sn, str) or sn not in snippets: E.append(f'{wr}: snippet {sn!r} has no file {KITS}/snippets/{sn}.md')
                else: used[sn] += 1
            free(wr, r, cs)
            good.append(r)
        areas.append(dict(a, requirements=good))
    for k, n in list(area_ids.items()) + list(req_ids.items()):
        if n > 1: E.append(f'{KITS}/dev-requirements.yaml: id {k} is used {n} times' + (' (duplicate requirement id)' if k.startswith('DEV-') else ''))
    for code, aa in codes.items():
        if len(aa) > 1: W.append(f'{KITS}/dev-requirements.yaml: the code {code} is used in several areas ({", ".join(sorted(aa))})')
    for k, sn in snippets.items():
        if not used[k]: W.append(f'{KITS}/snippets/{k}.md: no requirement uses this snippet')
        free(f'{KITS}/snippets/{k}.md', sn['raw'], [])
    for k, n in Counter(s['title'] for s in snippets.values()).items():
        if n > 1 and k: E.append(f'{KITS}/snippets: the title "{k}" is used by {n} snippets; give each its own')

    # ---- content.yaml
    if not isinstance(content, dict): E.append(f'{KITS}/content.yaml: must be a mapping with {", ".join(CONTENT_KEYS)}'); content = {}
    for k in content:
        if k not in CONTENT_KEYS and k != 'edition': E.append(f'{KITS}/content.yaml: unknown top-level key "{k}"{bk.hint(k, CONTENT_KEYS)}')
    # the kit's edition (optional; none = full) must be the edition of the build: the preview kit never builds the full edition's
    # pages (a checkout without _system/edition.yaml or edition.py), and the full kit never becomes the community edition's preview
    kit_ed, build_ed = content.get('edition', 'full'), (kb.get('edition') or {}).get('edition', 'full')
    if kit_ed not in KIT_EDITIONS: E.append(f'{KITS}/content.yaml: edition must be one of {", ".join(KIT_EDITIONS)}, found {kit_ed!r}')
    elif kit_ed != build_ed:
        E.append(f'{KITS}/content.yaml is the {kit_ed} edition\'s kit, but this build makes the {build_ed} edition'
                 + (': it needs _system/edition.yaml with "edition: community" and _system/edition.py (restore both files of the community branch)'
                    if kit_ed == 'community' else ': the community edition is built from the community kit (a short preview), never from the full kit'))
    for k in CONTENT_KEYS:
        if not isinstance(content.get(k), list): E.append(f'{KITS}/content.yaml: {k} must be a list' + (' (write [] when empty)' if k in content else ' (missing)'))
    rules = content.get('wording_rules') if isinstance(content.get('wording_rules'), list) else []
    if not rules and isinstance(content.get('wording_rules'), list): E.append(f'{KITS}/content.yaml: wording_rules is empty')
    for i, x in enumerate(rules, 1):
        if not isinstance(x, str) or not x.strip(): E.append(f'{KITS}/content.yaml: wording rule {i} must be a non-empty string')
    free(f'{KITS}/content.yaml wording_rules', rules, [])
    out = {'wording_rules': rules}
    for part, keys in ITEM_KEYS.items():
        seen, good = Counter(), []
        for x in content.get(part) if isinstance(content.get(part), list) else []:
            xid = (x.get('term') if part == 'glossary' else x.get('id')) if isinstance(x, dict) else None
            wx = f'{part[:-1] if part != "glossary" else "glossary term"} {xid}'
            if not rec(x, wx, keys, optional=('caution',) if part == 'angles' else ()): continue
            if part in ITEM_ID and not (isinstance(xid, str) and re.fullmatch(ITEM_ID[part] + r'-\d{3}', xid)):
                E.append(f'{wx}: id must look like {ITEM_ID[part]}-001')
            seen[str(xid).casefold() if part == 'glossary' else str(xid)] += 1
            cs = []
            if part == 'quotes':
                c = by_id.get(x.get('claim')) if isinstance(x.get('claim'), str) else None
                if not c: E.append(f'{wx}: claim {x.get("claim")!r} does not exist')
                elif x['claim'] not in public: E.append(f'{wx}: claim {x["claim"]} is private')
                elif not (c.get('quote') or '').strip(): E.append(f'{wx}: claim {x["claim"]} has no quote')
                elif c.get('who') == 'audience': E.append(f'{wx}: claim {x["claim"]} is an audience member\'s words, not a quote to publish')
                elif c.get('label') == 'analysis': E.append(f'{wx}: claim {x["claim"]} is the author\'s analysis, not a quote')
                else: cs = [c]
            elif part == 'angles':
                for k in ('title', 'hook', 'cta'): text(x, k, wx)
                if 'caution' in x and x['caution'] not in (None, '') and not isinstance(x['caution'], str): E.append(f'{wx}: caution must be a string')
                for k, allowed in (('audience', None), ('formats', FORMATS)):
                    v = x.get(k)
                    if not isinstance(v, list) or not v or any(not isinstance(y, str) or not y.strip() for y in v): E.append(f'{wx}: {k} must be a non-empty list of strings'); continue
                    bk.dups(v, f'{wx}: {k}', E)
                    if allowed: E.extend(f'{wx}: format {y!r} must be one of {", ".join(allowed)}' for y in v if y not in allowed)
                pts = x.get('points')
                if not isinstance(pts, list) or not pts: E.append(f'{wx}: points must be a non-empty list of {{text, claims}}'); pts = []
                for i, p in enumerate(pts, 1):
                    if rec(p, f'{wx} point {i}', ('text', 'claims')):
                        text(p, 'text', f'{wx} point {i}')
                        cs += cited(p.get('claims'), f'{wx} point {i}')
                if any(c.get('ver') == 'undocumented' for c in cs) and not (isinstance(x.get('caution'), str) and x['caution'].strip()):
                    W.append(f'{wx}: cites undocumented claims ({", ".join(c["id"] for c in cs if c.get("ver") == "undocumented")}); add a caution')
            else:
                for k in keys:
                    if k not in ('id', 'claims', 'status', 'use'): text(x, k, wx)
                cs = cited(x.get('claims'), wx)
                if part in ('facts', 'myths'): status(x.get('status'), wx, cs)
                if part == 'facts' and (not isinstance(x.get('use'), str) or x['use'] not in USES): E.append(f'{wx}: use must be one of {", ".join(USES)}, found {x.get("use")!r}')
            free(wx, x, cs)
            good.append(x)
        for k, n in seen.items():
            if n > 1: E.append(f'{KITS}/content.yaml: {part} lists {k} {n} times' + (' (terms must be unique)' if part == 'glossary' else ' (ids must be unique)'))
        out[part] = good
    tids = Counter()
    for x in out.get('glossary', []):
        if not isinstance(x.get('term'), str): continue
        tid = bk.node_slug(x['term'])
        if not tid: E.append(f'glossary term {x["term"]}: its id (term:<slug>) would be empty; write the term with at least one letter or digit')
        tids[tid] += 1
    for k, n in tids.items():
        if n > 1 and k: E.append(f'{KITS}/content.yaml: {n} glossary terms share the id term:{k} (the term in lower case, other characters '
                                 'turned into "-"); make the terms differ in letters or digits')
    dq = Counter(x['claim'] for x in out.get('quotes', []) if isinstance(x.get('claim'), str))
    for k, n in dq.items():
        if n > 1: E.append(f'{KITS}/content.yaml: quotes use claim {k} {n} times')

    # ---- differences.yaml (optional): the differences ledger, event against documentation
    diffs, dp = [], K / DIFF_FILE
    doc = bk.read_yaml(dp, E) if dp.exists() else {'differences': []}
    wd = f'{KITS}/{DIFF_FILE}'
    if dp.exists() and doc is not None and (not isinstance(doc, dict) or not isinstance(doc.get('differences'), list)):
        E.append(f'{wd}: needs differences: [...] (write [] when empty)'); doc = {'differences': []}
    for k in doc or {}:
        if k != 'differences': E.append(f'{wd}: unknown top-level key "{k}"{bk.hint(k, ("differences",))}')
    seen = Counter()
    for x in (doc or {}).get('differences') or []:
        xid = x.get('id') if isinstance(x, dict) else None
        wx = f'difference {xid}'
        if not rec(x, wx, DIFF_KEYS, optional=('pages',)): continue
        if not (isinstance(xid, str) and DIFF_ID.fullmatch(xid)): E.append(f'{wx}: id must look like DIF-01')
        seen[str(xid)] += 1
        for k in ('title', 'follow'): text(x, k, wx)
        roles = {}
        for k, want, what in (('event', EVENT, 'a slide or stage claim'), ('docs', ('docs',), "a docs claim (Google's documentation)"),
                              ('analysis', ('analysis',), 'an analysis claim')):
            v = x.get(k)
            if k not in x or (k == 'docs' and v == []): roles[k] = []; continue
            roles[k] = cited(v, wx, k)
            for c in roles[k]:
                if c.get('label') not in want: E.append(f'{wx}: {k} lists {c["id"]}, which is a {c.get("label")} claim; {k} takes {what}')
                elif k == 'event' and c.get('who') == 'audience': E.append(f'{wx}: event lists {c["id"]}, an audience question; list what was said or shown')
        pages = x.get('pages') if x.get('pages') is not None else []
        if not isinstance(pages, list) or any(not isinstance(p, str) for p in pages): E.append(f'{wx}: pages must be a list of source keys, e.g. [robots-spec]'); pages = []
        bk.dups(pages, f'{wx}: pages', E)
        for p in pages:
            if p not in sources: E.append(f'{wx}: unknown pages key {p} (add it to 20-claims/sources.yaml first)')
            elif (sources[p].get('kind') or 'google') != 'google': E.append(f'{wx}: pages key {p} is a press source; pages lists Google pages only')
        if not roles.get('docs') and not pages and isinstance(x.get('docs'), list): E.append(f"{wx}: needs Google's side: docs claims, or pages when no docs claim is in 20-claims/")
        ids = [c['id'] for r in roles.values() for c in r]
        for k, n in Counter(ids).items():
            if n > 1: E.append(f'{wx}: {k} is listed in more than one of event, docs and analysis')
        free(wx, x, [c for r in roles.values() for c in r])
        diffs.append(x)
    for k, n in seen.items():
        if n > 1: E.append(f'{wd}: id {k} is used {n} times (ids must be unique)')
    kb['kits'] = {'areas': areas, 'snippets': snippets, 'content': out, 'differences': diffs}
    briefs = root / '60-outputs' / 'content' / 'briefs.md'
    if briefs.exists():
        n = len(re.findall(r'^## ', briefs.read_text(encoding='utf-8'), re.M))
        W.append(f'60-outputs/content/briefs.md ({n} briefs) is replaced by the angles of {KITS}/content.yaml ({len(out.get("angles", []))}); '
                 'this build removes it (git keeps the old version)')


# ---------------------------------------------------------------- rendering helpers
def anchor(s):  # the id GitHub gives a Markdown heading
    return re.sub(r'[^\w\- ]', '', s.strip().lower()).replace(' ', '-')


def pl(n, word, many=None):
    return f'{n} {word if n == 1 else many or word + "s"}'


def fence(code, lang=''):
    n = max([3] + [len(x) + 1 for x in re.findall(r'`{3,}', code)])
    return f"{'`' * n}{lang}\n{code}\n{'`' * n}"


def md_block(s, bk):
    """Several lines of plain text: each line made Markdown-safe, list markers and fenced code kept."""
    out, code = [], None
    for ln in str(s).strip('\n').split('\n'):
        if code is not None:
            out.append(ln)
            if ln.strip().startswith(code) and not ln.strip().strip(code[0]): code = None
            continue
        m = FENCE.fullmatch(ln.strip())
        if m and ln.lstrip().startswith(('```', '~~~')): code = m[1]; out.append(ln.strip()); continue
        m = re.match(r'(\s*)([-*+] |\d+[.)] )?(.*)', ln)
        out.append(m[1] + (m[2] or '') + bk.md(m[3]) if m[3].strip() else '')
    if code is not None: out.append(code)
    return '\n'.join(out)


def csv_text(rows):
    buf = io.StringIO(newline='')
    w = csv.writer(buf, lineterminator='\n')
    w.writerows(rows)
    return buf.getvalue()


# ---------------------------------------------------------------- build
def build(root, kb, bk, meta):
    """Write 60-outputs/dev/, 60-outputs/content/ and the two JSON files of the agent pack. meta: version, through, through_txt."""
    kit, S, sources = kb['kits'], kb['sessions'], kb['sources']
    CL = {c['id']: c for c in kb['claims'] if c.get('private') is not True}
    _, google = people(S)
    event = kb['event'].get('name', '')
    ED = kb.get('edition') or {}
    community = ED.get('edition') == 'community'  # the community edition: the media kit is a preview (see COMMUNITY_NOTE)
    version, through, through_txt = meta['version'], meta['through'], meta['through_txt']
    day = lambda c: S[c['s']]['day']
    I = kit_items(kb, bk)
    tp = lambda kind, key: I[f'{PREFIX[kind]}:{key}']['topics']  # the item's topics, from its claims
    IE = kb.get('item_entities') or {}  # set by build_kb.py from 20-claims/entities.yaml: the things each item is about
    te = lambda kind, key: IE.get(f'{PREFIX[kind]}:{key}', [])
    defines = {}  # glossary term id -> the things it defines (entities.yaml `glossary`)
    for x in kb.get('entities', []):
        if x.get('glossary'): defines.setdefault(x['glossary'], []).append(x['id'])

    def credit(c):
        if c['label'] == 'analysis': return f'{bk.AUTHOR} (author)'
        w = who_short(c, S, google, sources)
        return f'{w} at {event} (Day {day(c)})' if c['label'] in EVENT else w

    def ver_text(c):
        return 'is the press report' if c['ver'] == 'source' and c['label'] == 'press' else bk.VER[c['ver']] or 'nothing to verify'

    def src(k):
        s = sources[k]
        return {'key': k, 'title': s['title'], 'url': s['url'], 'publisher': s['publisher'], 'kind': s.get('kind') or 'google', 'checked': str(s['checked'])}

    def ref(cid):
        c = CL[cid]
        return {'id': cid, 'day': day(c), 'session_id': c['s'], 'session': S[c['s']]['title'], 'label': c['label'], 'label_meaning': bk.LABEL_HELP[c['label']],
                'verification': c['ver'], 'verification_meaning': ver_text(c), 'text': bk.nt(c['text']),
                'quote': bk.nt(c.get('quote') or '').strip('"'), 'quote_checked': c.get('quote_checked') is True, 'credit': credit(c),
                'speaker': proven(c, S), 'sources': [src(k) for k in c.get('src', [])]}

    def ev_md(cid):
        c = CL[cid]
        w = who_short(c, S, google, sources)
        where = f"{SAYS[c['label']]}, Day {day(c)} ({w})" if c['label'] in EVENT else SAYS[c['label']] + (f' ({w})' if c['label'] != 'analysis' else '')
        v = bk.VER[c['ver']] if c['ver'] not in ('source', 'n/a') else ''
        return f"- `{cid}` {bk.md(where)}{', ' + v if v else ''}: {bk.md(c['text'])}"

    def docs_md(keys, lead='Google documentation'):
        keys = list(dict.fromkeys(keys))
        return [f"- {lead}: [{bk.md(sources[k]['title'])}]({sources[k]['url']}) ({bk.md(sources[k]['publisher'])}, checked {sources[k]['checked']})" for k in keys]

    def google_docs(cids):
        return [k for x in cids for k in CL[x].get('src', []) if (sources[k].get('kind') or 'google') == 'google']

    def press_docs(cids):
        return [k for x in cids for k in CL[x].get('src', []) if sources[k].get('kind') == 'press']

    def head(title, lead):
        return [GEN, f'# {title}', '', lead, '', f'Version {version} · data through {through_txt}. Built from `25-kits/` and the claims in `20-claims/`.', '']

    def readme_lead(first, rest):  # a kit README: the purpose in bold, then the same lines as head()
        return f'**{first}**\n\n{rest}\n\nVersion {version} · data through {through_txt}. Built from `25-kits/` and the claims in `20-claims/`.'

    snippets = kit['snippets']
    reqs = [(a, r) for a in kit['areas'] for r in a['requirements']]
    used_by = {}
    for a, r in reqs:
        if r.get('snippet'): used_by.setdefault(r['snippet'], []).append(r['id'])
    order = list(used_by) + sorted(k for k in snippets if k not in used_by)  # in the order the guide first uses them

    # ---------------- the ledgers (knowledge graph phase 3): computed here, counted in the READMEs, written at the end
    fname = lambda c: f"{c['session_id']}-{bk.slug(S[c['session_id']]['title'])}.md"
    LG = ledgers(kb, bk, meta, ref, credit)
    LP = ledger_pages(LG, bk, meta, {'maps_claim': lambda c: f"../40-sessions/day{c['day']}/{fname(c)}", 'dev_claim': lambda c: f'../agent-pack/sessions/{fname(c)}',
                                     'content_claim': lambda c: f'../agent-pack/sessions/{fname(c)}', 'content_card': lambda e: f'../agent-pack/entities/{e}.md'})
    n_diff, n_q, n_t = len(LG['differences']['rows']), len(LG['questions']['audience']), len(LG['questions']['things'])

    # ---------------- agent-pack / dev-requirements.json
    def snip(k):
        s = snippets[k]
        return {'key': k, 'title': bk.nt(s['title']), 'text': bk.nt(s['text']), 'code': [{'lang': b['lang'], 'code': b['code'], 'note': bk.nt(b['note'])} for b in s['code']],
                'used_by': used_by.get(k, [])}
    dj = {'version': version, 'data_through': through, 'event': event,
          'levels': LEVELS, 'statuses': {k: {'label': v[0], 'meaning': v[1]} for k, v in STATUS.items()},
          'areas': [{'id': a['id'], 'title': bk.nt(a['title']), 'intro': a['intro'].strip(), 'requirements': [
              {'id': r['id'], 'level': r['level'], 'title': bk.nt(r['title']), 'why': r['why'].strip(), 'how': r['how'].strip(), 'test': r['test'].strip(),
               'status': r['status'], 'status_label': STATUS[r['status']][0], 'snippet': r.get('snippet'), 'claims': [ref(x) for x in r['claims']],
               'topics': tp('requirement', r['id']), 'docs': [src(k) for k in r.get('docs') or []], 'entities': te('requirement', r['id'])}
              for r in a['requirements']]} for a in kit['areas']],
          'snippets': [snip(k) for k in order]}
    P = root / '60-outputs' / 'agent-pack'
    bk.write(P / 'dev-requirements.json', json.dumps(dj, indent=2, ensure_ascii=False) + '\n')

    # ---------------- 60-outputs/dev
    D = root / '60-outputs' / 'dev'
    bk.fresh(D)
    lv = Counter(r['level'] for _, r in reqs)
    st = Counter(r['status'] for _, r in reqs)
    rd = ["## What's here", '', '| File | Use it for |', '| --- | --- |',
          f'| [`implementation-guide.md`](implementation-guide.md) | The full kit: {len(reqs)} requirements in {len(kit["areas"])} areas, with why, how, a test and evidence |',
          '| [`requirements.csv`](requirements.csv) | One row per requirement, with the claims and topics it rests on, for Jira, Linear, GitHub Issues or a spreadsheet |',
          f'| [`snippets.md`](snippets.md) | {len(snippets)} copy-paste code snippets, such as HTML, JSON-LD, robots.txt, HTTP headers, server configuration and XML sitemaps |',
          f"| [`pre-launch-checklist.md`](pre-launch-checklist.md) | The release review: the {lv['MUST'] + lv['AVOID']} MUST and AVOID items, with checkboxes |",
          f"| [`differences.md`](differences.md) | The differences ledger: {pl(n_diff, 'place')} where the event and Google's documentation differ, and what to "
          'follow; then the claims linked as contradicting or updating, and the claims that say they are uncertain |',
          '| [`dev-requirements.json`](../agent-pack/dev-requirements.json) | In the agent pack: the same data, with claim texts and source links resolved |', '',
          f"{sum(1 for _, r in reqs if r.get('snippet'))} of the {len(reqs)} requirements come with code: the guide shows it under the requirement, "
          'and `snippets.md` collects every snippet. The JSON file is for scripts and AI agents.', '',
          '## Levels', '', '| Level | Meaning | Count |', '| --- | --- | ---: |'] + [f'| **{k}** | {v} | {lv[k]} |' for k, v in LEVELS.items()]
    rd += ['', '## Status', '', '| Status | Meaning | Count |', '| --- | --- | ---: |'] + [f'| {v[0]} (`{k}`) | {v[1]} | {st[k]} |' for k, v in STATUS.items()]
    rd += ['', '## How to use it', '',
           '1. Read the area introductions in `implementation-guide.md`, then the requirements of the areas your project touches.',
           '2. Import `requirements.csv` into your tracker: one ticket per row, the `test` column as the acceptance criterion, `level` as the priority. '
           'The `claims` column lists the claim IDs the requirement rests on, `topics` the topics of those claims (most frequent first), and `docs` the Google pages.',
           '3. Copy code from `snippets.md`; replace the example.com values with your own.',
           '4. Before a launch or a migration, go through `pre-launch-checklist.md` with the person who signs off the release.',
           '5. Every requirement cites claim IDs such as `D2-C264`. Look them up in [`60-outputs/agent-pack/claims.jsonl`](../agent-pack/claims.jsonl) or on the web '
           'edition (`claims.html#D2-C264`) to see exactly what was said and how it stands against the documentation.',
           f'6. A requirement marked *{STATUS["event-only"][0]}* is not in Google\'s documentation: treat it as strong guidance from the event, and re-test it.', '',
           '## Requirements per area', '', '| Area | MUST | SHOULD | MAY | AVOID | Total |', '| --- | ---: | ---: | ---: | ---: | ---: |']
    for a in kit['areas']:
        c = Counter(r['level'] for r in a['requirements'])
        rd.append(f"| [{bk.cell(a['title'])}](implementation-guide.md#{anchor(bk.nt(a['title']))}) | " + ' | '.join(str(c[k]) for k in LEVELS) + f" | {len(a['requirements'])} |")
    rd += ['', '## Changing the kit', ''] + bk.generated_note('`_system/kits.py` from `25-kits/`', '`25-kits/dev-requirements.yaml` or `25-kits/snippets/`') + [
           '> The build rewrites every file in this folder. See step 7 of `_system/PLAYBOOK.md`.']
    bk.write(D / 'README.md', bk.readme(2, [('Knowledge base', '../../README.md'), ('60-outputs', '../README.md'), ('dev', None)], GEN, 'Developer kit',
                                        readme_lead(f"Requirements for building and launching sites that Google can crawl, render, index and show well, drawn from "
                                                    f"{bk.md(event)} and checked against Google's documentation.",
                                                    'Every requirement says why it matters, how to build it and how to test it, and cites the claims and Google pages it rests on.'),
                                        rd,
                                        bk.nav(('Field guides', '../pdf/README.md'), ('60-outputs', '../README.md'), ('Media kit', '../content/README.md')),
                                        art='60-outputs-dev'))

    def snippet_md(k, level='####'):
        s = snippets[k]
        out = [f"{level} Snippet: {bk.md(s['title'])}", ''] + ([bk.md(s['text']), ''] if s['text'] else [])
        for b in s['code']: out += ([bk.md(b['note']), ''] if b['note'] else []) + [fence(b['code'], b['lang']), '']
        return out

    g = head('Implementation guide', f"{len(reqs)} requirements in {len(kit['areas'])} areas. Levels: " + ', '.join(f'**{k}** ({v.split(":")[0].lower()})' for k, v in LEVELS.items())
             + f". Status: *{STATUS['documented'][0]}* (a cited Google page states or supports it) or *{STATUS['event-only'][0]}* (not in Google's documentation).")
    g += ['## Contents', ''] + [f"- [{bk.md(a['title'])}](#{anchor(bk.nt(a['title']))}) ({len(a['requirements'])})" for a in kit['areas']] + ['']
    for a in kit['areas']:
        g += [f"## {bk.md(a['title'])}", '', md_block(a['intro'], bk), '']
        for r in a['requirements']:
            g += [f"### {r['id']} {bk.md(r['title'])}", '', f"**{r['level']}** · *{STATUS[r['status']][0]}*", '',
                  '**Why.** ' + md_block(r['why'], bk), '', '**How.**', '', md_block(r['how'], bk), '', '**Test.** ' + md_block(r['test'], bk), '']
            if r.get('snippet'): g += snippet_md(r['snippet'])
            g += ['**Evidence**', ''] + [ev_md(x) for x in r['claims']] + docs_md(r.get('docs') or []) + ['']
    bk.write(D / 'implementation-guide.md', '\n'.join(g))

    rows = [['id', 'area', 'level', 'title', 'why', 'how', 'test', 'status', 'snippet', 'claims', 'topics', 'docs', 'entities']]
    rows += [[r['id'], bk.nt(a['title']), r['level'], bk.nt(r['title']), r['why'].strip(), r['how'].strip(), r['test'].strip(), r['status'],
              bk.nt(snippets[r['snippet']]['title']) if r.get('snippet') else '', '; '.join(r['claims']), '; '.join(tp('requirement', r['id'])),
              '; '.join(sources[k]['url'] for k in r.get('docs') or []), '; '.join(e['id'] for e in te('requirement', r['id']))]
             for a, r in reqs]
    bk.write(D / 'requirements.csv', csv_text(rows))

    sm = head('Code snippets', f"{len(snippets)} snippets to copy into templates and server configuration. Replace example.com and the sample values with your own, "
              'then test the page as its requirement says.')
    sm += ['## Contents', ''] + [f"- [{bk.md(snippets[k]['title'])}](#{anchor('Snippet: ' + snippets[k]['title'])})" for k in order] + ['']
    for k in order:
        sm += snippet_md(k, '##') + ['Used by: ' + (', '.join(f'`{x}`' for x in used_by.get(k, [])) or 'no requirement yet') + '.', '']
    bk.write(D / 'snippets.md', '\n'.join(sm))

    cl = head('Pre-launch checklist', 'Every MUST and AVOID requirement of the developer kit, for the release review. Tick a MUST item when it is in place '
              'and an AVOID item when you have confirmed the site does not do it. The test for each item is in the implementation guide.')
    for a in kit['areas']:
        items = [r for r in a['requirements'] if r['level'] in ('MUST', 'AVOID')]
        if not items: continue
        cl += [f"## {bk.md(a['title'])}", '']
        cl += [f"- [ ] **{r['level']}** `{r['id']}` {bk.md(r['title'])}" + (' *(said at Search Central Live)*' if r['status'] == 'event-only' else '')
               + f" ([test](implementation-guide.md#{anchor(r['id'] + ' ' + bk.nt(r['title']))}))" for r in items] + ['']
    bk.write(D / 'pre-launch-checklist.md', '\n'.join(cl))

    # ---------------- content
    ct = kit['content']
    quote = lambda c: quote_text(c, bk)
    lib = {'version': version, 'data_through': through, 'event': event, 'wording_rules': [bk.nt(x) for x in ct['wording_rules']],
           'statuses': {k: {'label': v[0], 'meaning': v[1]} for k, v in GRADES.items()},
           'facts': [{'id': f['id'], 'statement': bk.nt(f['statement']), 'status': f['status'], 'status_label': STATUS[f['status']][0], 'use': f['use'],
                      'claims': [ref(x) for x in f['claims']], 'topics': tp('fact', f['id']), 'entities': te('fact', f['id'])} for f in ct['facts']],
           'myths': [{'id': m['id'], 'myth': bk.nt(m['myth']), 'fact': bk.nt(m['fact']), 'status': m['status'], 'status_label': STATUS[m['status']][0],
                      'claims': [ref(x) for x in m['claims']], 'topics': tp('myth', m['id']), 'entities': te('myth', m['id'])} for m in ct['myths']],
           'quotes': [{'id': q['id'], 'quote': quote(CL[q['claim']]), **{k: v for k, v in ref(q['claim']).items() if k not in ('quote', 'id')}, 'claim': q['claim'],
                       'topics': tp('quote', q['id']), 'entities': te('quote', q['id'])} for q in ct['quotes']],
           'angles': [{'id': x['id'], 'title': bk.nt(x['title']), 'audience': x['audience'], 'formats': x['formats'], 'hook': bk.nt(x['hook']),
                       'points': [{'text': bk.nt(p['text']), 'status': grade_point([CL[i] for i in p['claims']]), 'claims': [ref(i) for i in p['claims']]} for p in x['points']],
                       'caution': bk.nt(x.get('caution') or ''), 'cta': bk.nt(x['cta']), 'topics': tp('angle', x['id']), 'entities': te('angle', x['id'])} for x in ct['angles']],
           'glossary': [{'id': bk.node_slug(t['term']), 'term': bk.nt(t['term']), 'definition': bk.nt(t['definition']), 'claims': [ref(i) for i in t['claims']],
                         'topics': tp('term', bk.node_slug(t['term'])), 'entities': te('term', bk.node_slug(t['term'])),
                         'defines': defines.get(bk.node_slug(t['term']), [])}
                        for t in sorted(ct['glossary'], key=lambda t: (bk.nt(t['term']).casefold(), t['term']))]}
    if community:  # right after event, so a reader of the library sees it first; the full edition's file has neither key
        lib = {**{k: lib[k] for k in ('version', 'data_through', 'event')}, 'edition': 'community', 'note': COMMUNITY_NOTE,
               **{k: v for k, v in lib.items() if k not in ('version', 'data_through', 'event')}}
    lj = json.dumps(lib, indent=2, ensure_ascii=False) + '\n'
    bk.write(P / 'content-library.json', lj)
    C = root / '60-outputs' / 'content'
    bk.fresh(C)
    bk.write(C / 'content-library.json', lj)

    def evidence(cids):
        return [ev_md(x) for x in cids] + docs_md(google_docs(cids)) + docs_md(press_docs(cids), 'Press')

    def fact_md(f, level='###'):
        return [f"{level} {f['id']}: {bk.md(bk.nt(f['statement']))}", '', f"*{STATUS[f['status']][0]}*", ''] + evidence(f['claims']) + ['']

    def myth_md(m, level='##'):
        return [f"{level} {m['id']}: {bk.md(bk.nt(m['myth']))}", '', f"**Myth:** {bk.md(m['myth'])}", '', f"**Fact:** {bk.md(m['fact'])}", '',
                f"*{STATUS[m['status']][0]}*", ''] + evidence(m['claims']) + ['']

    def angle_md(x, level='##'):
        out = [f"{level} {x['id']}: {bk.md(x['title'])}", '', f"**Audience:** {bk.md(', '.join(x['audience']))} · **Formats:** {', '.join(FORMATS[f] for f in x['formats'])}", '',
               f"**Hook:** {bk.md(x['hook'])}", '', '**Points:**', '']
        for i, p in enumerate(x['points'], 1):
            out.append(f"{i}. {bk.md(p['text'])} *({GRADES[grade_point([CL[c] for c in p['claims']])][0]}: " + ', '.join(f'`{c}`' for c in p['claims']) + ')*')
        out += ['']
        if (x.get('caution') or '').strip(): out += [f"**Caution:** {bk.md(x['caution'])}", '']
        return out + [f"**Call to action:** {bk.md(x['cta'])}", '', '**Evidence:**', ''] + evidence(list(dict.fromkeys(c for p in x['points'] for c in p['claims']))) + ['']

    def quote_md(q, level='##'):
        c = CL[q['claim']]
        out = [f"{level} {q['id']}", '', f'> "{bk.md(quote(c))}"', '', f"Credit: {bk.md(credit(c))}" + (f" · Named speaker: {bk.md(proven(c, S))}" if proven(c, S) else ''), '',
               f"`{c['id']}` · {SAYS[c['label']]} · " + ('wording checked' if c.get('quote_checked') else 'wording not yet checked against the slide or recording')
               + (f" · {bk.VER[c['ver']]}" if bk.VER[c['ver']] and c['ver'] != 'source' else ''), '', f"Context: {bk.md(c['text'])}", '']
        return out + docs_md(google_docs([c['id']])) + ([''] if google_docs([c['id']]) else [])

    lead = 'Every item cites the claims it rests on.'
    ev_name = bk.md(event)
    whats = ["## What's here", '', '| File | Use it for |', '| --- | --- |']
    if community:
        fk = ED.get('full_kit') or {}
        company, linkedin = ED.get('company') or {}, ED.get('linkedin') or ''
        say = lambda n, w: (WORDS[n] if n < len(WORDS) else str(n)) + ' ' + pl(n, w).split(' ', 1)[1]  # "two myths", "one story angle"
        taste = (f"{say(len(ct['facts']), 'fact')}, {say(len(ct['myths']), 'myth')}, {say(len(ct['angles']), 'story angle')} and "
                 f"{say(len(ct['quotes']), 'quote')} from the full kit, as the kit holds them: each with the claims it rests on, its label and the credit line to use.")
        cr = ['## A small taste', '', taste[:1].upper() + taste[1:], '']
        for ptitle, part, render in (('Facts', 'facts', fact_md), ('Myths', 'myths', myth_md),
                                     ('Story angle' if len(ct['angles']) == 1 else 'Story angles', 'angles', angle_md), ('Quotes', 'quotes', quote_md)):
            if ct[part]: cr += [f'### {ptitle}', ''] + [y for x in ct[part] for y in render(x, '####')]
        cr += ['## Want to create content from it, at scale?', '',
               "We help companies turn this knowledge base into a content engine: briefs, articles, social posts and newsletters, generated with the wording "
               "rules, credit lines and verification built in, reviewed for quality and written in your brand's voice.", '',
               f"Get in touch: [{link_text(company.get('name', ''), bk)}]({company.get('url', '')}) · [LinkedIn]({linkedin})", '',
               f"The glossary stays open for everyone: [`glossary.md`](glossary.md) holds all {pl(len(ct['glossary']), 'term')} in plain English.", '']
        cr += whats + [f"| [`glossary.md`](glossary.md) | {len(ct['glossary'])} terms in plain English. |",
                       '| [`content-library.json`](content-library.json) | The wording rules, the glossary and the preview above for AI writing tools, with claims and sources '
                       'resolved and the topics each item touches |', '',
                       '> [!IMPORTANT]', '> This kit comes from an independent attendee knowledge base, not from Google. It holds paraphrases, quotations '
                       'of 25 words or fewer and links to Google\'s public documentation only: no slide photos, recordings or transcripts. '
                       'Credit each item as the credit lines below say.', '']
        named = '(`speaker` in `content-library.json`). '
        rl = readme_lead(
            'The full media kit is not part of this community edition.',
            f"Behind this page sits a complete kit for content teams: {fk.get('facts', 0)} facts with safe wording, {fk.get('myths', 0)} myths with the facts "
            f"that answer them, {fk.get('angles', 0)} story angles, {fk.get('quotes', 0)} short quotations with their credit lines, every figure with its scope "
            f"({fk.get('stat_facts', 0)}), and the audience's questions with Google's answers ({fk.get('audience_questions', 0)}). Each item is tied to its claims, "
            "labelled, and graded against Google's documentation, so writers know what can be said as Google's position and what was only said on stage.")
    else:
        cr = whats + [
              f"| [`fact-sheet.md`](fact-sheet.md) | {len(ct['facts'])} headline-ready facts, grouped as stats, headlines and context. |",
              f"| [`myths-and-facts.md`](myths-and-facts.md) | {len(ct['myths'])} myths with the fact that answers them. |",
              f"| [`story-angles.md`](story-angles.md) | {len(ct['angles'])} angles: audience, formats, hook, points, cautions and a call to action. |",
              f"| [`quotes.md`](quotes.md) | {len(ct['quotes'])} short quotations (25 words or fewer) with the credit line to use. |",
              f"| [`glossary.md`](glossary.md) | {len(ct['glossary'])} terms in plain English. |",
              f"| [`questions.md`](questions.md) | The question bank: {pl(n_q, 'audience question')} with their answers, and \"What did Google say about it?\" for "
              f"{pl(n_t, 'thing')} the event talked about, documented first. |",
              '| [`questions.json`](questions.json) | The question bank for AI tools and agents, with a citation for every claim. |',
              f"| [Numbers registry](../../50-maps/numbers.md) | In the maps: the {sum(1 for f in ct['facts'] if f['use'] == 'stat')} stat facts with their figures, "
              'scope, claims and credit, and the figures in the claims that no fact cites yet. |',
              '| [`content-library.json`](content-library.json) | All of the above for AI content tools, with claims and sources resolved and the topics each item touches |', '',
              '> [!IMPORTANT]', '> This kit comes from an independent attendee knowledge base, not from Google. It holds paraphrases, quotations '
              'of 25 words or fewer and links to Google\'s public documentation only: no slide photos, recordings or transcripts. '
              'Credit each item as the credit lines below say.', '']
        named = '(`speaker` in `content-library.json`, "Named speaker" in `quotes.md`). '
        rl = readme_lead(f'Facts, myths, story angles, quotes and a glossary from {ev_name}, ready for posts, articles, newsletters, videos and talks.',
                         "Each item is tied to claim IDs and labelled by how far Google's documentation backs it.")
    cr += ['## Credit lines', '', f'- What Google said or showed at the event: "Google at {ev_name} (Day N)".',
           f'- What a community speaker said: "a community speaker at {ev_name} (Day N)". Never present it as Google\'s position.',
           f'- Where the credit is "a speaker at {ev_name} (Day N)", the knowledge base does not record whether a Googler or a community speaker said it '
           '(a point from a session that was not recorded, or a lightning slot with a Google host): write "said at the event" and never attribute it to Google.',
           "- Google's documentation: name the page and link it.",
           '- A speaker\'s name appears only where the content library gives one ' + named +
           'Everywhere else, leave the name out: who said it matters less than what was said and how well it is documented.', '']
    cr += ['## Labels', '', '| Label | Meaning |', '| --- | --- |'] + [f'| {v[0]} | {v[1]} |' for v in GRADES.values()]
    cr += ['', '## Wording rules', ''] + [f'{i}. {bk.md(x)}' for i, x in enumerate(ct['wording_rules'], 1)]
    cr += ['', '## Changing the kit', ''] + bk.generated_note('`_system/kits.py` from `25-kits/`', '`25-kits/content.yaml`') + [
           '> The build rewrites every file in this folder. See step 7 of `_system/PLAYBOOK.md`.']
    bk.write(C / 'README.md', bk.readme(2, [('Knowledge base', '../../README.md'), ('60-outputs', '../README.md'), ('content', None)], GEN, 'Media kit', rl, cr,
                                        bk.nav(('Developer kit', '../dev/README.md'), ('60-outputs', '../README.md'), ('Agent pack', '../agent-pack/INDEX.md')),
                                        art='60-outputs-content'))

    if not community:  # the media kit's own files; the community edition shows its preview in the README above
        fs = head('Fact sheet', f'{len(ct["facts"])} facts. {lead} *{STATUS["documented"][0]}*: Google\'s documentation states or supports it. '
                  f'*{STATUS["event-only"][0]}*: present it as said at Search Central Live, never as documented policy.')
        for u, utitle in USES.items():
            items = [f for f in ct['facts'] if f['use'] == u]
            if not items: continue
            fs += [f'## {utitle}', '']
            for f in items: fs += fact_md(f)
        bk.write(C / 'fact-sheet.md', '\n'.join(fs))

        mf = head('Myths and facts', f'{len(ct["myths"])} myths heard in the industry, each answered from the event and the documentation. {lead}')
        for m in ct['myths']: mf += myth_md(m)
        bk.write(C / 'myths-and-facts.md', '\n'.join(mf))

        sa = head('Story angles', f'{len(ct["angles"])} angles that can become a post, an article, a newsletter, a video or a talk. Each point is labelled by how far '
                  "Google's documentation backs it; follow the caution where there is one.")
        for x in ct['angles']: sa += angle_md(x)
        bk.write(C / 'story-angles.md', '\n'.join(sa))

        qm = head('Quotes', f'{len(ct["quotes"])} quotations of 25 words or fewer. Quote them exactly, with the credit line given; "wording checked" means the words '
                  'were compared with the slide or the recording.')
        for q in ct['quotes']: qm += quote_md(q)
        bk.write(C / 'quotes.md', '\n'.join(qm))

    gl = head('Glossary', f'{len(ct["glossary"])} terms in plain English. {lead}')
    for t in lib['glossary']:
        gl += [f"**{bk.md(t['term'])}**: {bk.md(t['definition'])} (" + ', '.join(f"`{c['id']}`" for c in t['claims']) + ')', '']
    bk.write(C / 'glossary.md', '\n'.join(gl))

    # ---------------- the ledgers: 50-maps, the developer kit, the media kit and the agent pack
    js = lambda o: json.dumps(o, indent=2, ensure_ascii=False) + '\n'
    if community: (root / '50-maps' / 'numbers.md').unlink(missing_ok=True)  # the numbers registry and the question bank belong to the full media kit
    else: bk.write(root / '50-maps' / 'numbers.md', LP['numbers'] + '\n')
    bk.write(root / '50-maps' / 'differences.md', LP['differences'] + '\n')
    bk.write(D / 'differences.md', LP['dev_differences'] + '\n')
    if not community:
        bk.write(C / 'questions.md', LP['questions'] + '\n')
        bk.write(C / 'questions.json', js(LG['questions']))
        bk.write(P / 'question-bank.json', js(LG['questions']))  # not questions.json: no file of the pack may look like the eval's answer key
        bk.write(P / 'numbers.json', js(LG['numbers']))
    bk.write(P / 'differences.json', js(LG['differences']))
    print(f"OK: kits: {pl(len(reqs), 'requirement')} in {pl(len(kit['areas']), 'area')} ({lv['MUST']} MUST, {lv['AVOID']} AVOID), {pl(len(snippets), 'snippet')}; "
          + ('community edition, media kit preview: ' if community else '') +
          f"{pl(len(ct['facts']), 'fact')}, {pl(len(ct['myths']), 'myth')}, {pl(len(ct['angles']), 'angle')}, {pl(len(ct['quotes']), 'quote')}, "
          f"{pl(len(ct['glossary']), 'glossary term')}.")
    N_, D_ = LG['numbers'], LG['differences']
    if community:
        print(f"OK: ledgers: {pl(n_diff, 'difference')}, {pl(len(D_['pairs']), 'linked pair')} and {pl(len(D_['hedged']), 'hedged claim')} in "
              '50-maps/differences.md; the numbers registry and the question bank belong to the full media kit and are not written in the community edition.')
        return
    print(f"OK: ledgers: {pl(len(N_['facts']), 'stat fact')} in 50-maps/numbers.md; {pl(n_diff, 'difference')}, {pl(len(D_['pairs']), 'linked pair')} and "
          f"{pl(len(D_['hedged']), 'hedged claim')} in 50-maps/differences.md; {pl(n_q, 'audience question')} and {pl(n_t, 'thing')} in 60-outputs/content/questions.md.")
    if N_['candidates']:
        print(f"NOTE: {pl(len(N_['candidates']), 'public claim')} state{'s' * (len(N_['candidates']) == 1)} a figure that no stat fact cites: candidates for the media kit, listed at the end of "
              '50-maps/numbers.md.')


# ---------------------------------------------------------------- knowledge graph phase 3: the ledgers
# Three derived products, written by build() after the kits (plan B4, "Phase 3 set"). Everything is built from the claims, the kits and
# 25-kits/differences.yaml; the ledger's rows are the only hand-written part. Public claims only; no clock; in the kits' own order or in
# claim order, so a rebuild is byte-identical.
#   numbers registry    the use: stat facts with their figures, wording (which keeps the scope), claims, status, credit and things;
#                       plus the public claims that state a figure no stat fact cites (candidates for the media kit)
#   differences ledger  the rows of 25-kits/differences.yaml, then the claims linked by contradicts or updates, then the hedged claims
#   question bank       the audience questions with their answers, and per thing "What did Google say about X?"
_QUAL = r'(?:(?:more than|over|about|around|roughly|nearly|almost|up to|at least|at most|under|fewer than|less than|exactly)\s+)?'
_NUM = r'(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?'
_UNIT = (r'(?:\s?(?:%|percent\b|per cent\b)|x\b|\s?(?:px|KiB|KB|MB|GB)\b|\s(?:times|thousand|million|billion|trillion|milliseconds?|seconds?|'
         r'minutes?|hours?|days?|weeks?|months?|years?(?![\s-]+olds?\b)|pixels?|words?|characters?)\b)')
FIGURE = re.compile(rf'(?<![\w.,/:-]){_QUAL}(?P<n>{_NUM})(?:\s?(?:-|–|to)\s?{_NUM})?(?:(?P<u>{_UNIT})|(?=[^\w%]|$))', re.I)
HEDGE = re.compile(r'\b(uncertain|unclear|could not be confirmed|not clear|inaudible|unintelligible recording|recordings disagree|best reading)', re.I)
TOP_SAID = 3  # claims per list in "What did Google say about X?"
LABEL_WORD = {'slide': 'slide', 'stage': 'stage', 'docs': 'docs', 'press': 'press', 'analysis': 'analysis'}


def figures(text):
    """The figures a text states, as written, each once: a number with a unit (%, times, million, hours, px ...) or a number written
    with thousands separators (10,000), keeping a range (1-2 weeks, 45 to 90 minutes) and a qualifier (more than, about, up to ...).
    Bare numbers (years, dates, days, status codes, version numbers) are not figures."""
    return list(dict.fromkeys(m[0].strip() for m in FIGURE.finditer(' '.join(str(text or '').split())) if m['u'] or ',' in m['n']))


def ledgers(kb, bk, meta, ref, credit):
    """The data of the three Phase 3 products (nothing is written here). ref(cid) and credit(c) are build()'s claim record and credit line."""
    S, sources = kb['sessions'], kb['sources']
    public = [c for c in kb['claims'] if c.get('private') is not True]
    CL, order = {c['id']: c for c in public}, {c['id']: i for i, c in enumerate(public)}
    _, google = people(S)
    ct, I = kb['kits']['content'], kit_items(kb, bk)
    IE = kb.get('item_entities') or {}
    EN = kb.get('entity_model') or {'list': [], 'by_id': {}}
    ename = lambda e: EN['by_id'][e]['name'] if e in EN['by_id'] else e
    used = Counter(x for it in I.values() for x in it['claims'])
    M = kb.get('mentions') or {}
    trank = {t: i for i, t in enumerate(kb['topics'])}
    head = {'version': meta['version'], 'data_through': meta['through']}
    rule = lambda n: bk.nt(ct['wording_rules'][n - 1]) if len(ct['wording_rules']) >= n else ''

    def cref(cid):
        return dict(ref(cid), by=who_short(CL[cid], S, google, sources), cite=bk.claim_cite(CL[cid], kb, google))

    def topics_of(cids):
        n = Counter(t for x in cids for t in CL[x]['topics'])
        return sorted(n, key=lambda t: (-n[t], trank[t]))

    def things_of(cids):
        n = Counter(e for x in cids for e in M.get(x, {}))
        return [{'id': e, 'name': ename(e), 'count': n[e]} for e in sorted(n, key=lambda e: (-n[e], e))]

    # ---- numbers registry
    stat_cited = {x for f in ct['facts'] if f['use'] == 'stat' for x in f['claims']}
    facts = []
    for f in ct['facts']:
        if f['use'] != 'stat': continue
        facts.append({'id': f['id'], 'figures': figures(f['statement']), 'statement': bk.nt(f['statement']), 'status': f['status'],
                      'status_label': STATUS[f['status']][0], 'credit': list(dict.fromkeys(credit(CL[x]) for x in f['claims'])),
                      'claims': [cref(x) for x in f['claims']], 'topics': I[f"fact:{f['id']}"]['topics'],
                      'entities': [{'id': e['id'], 'name': ename(e['id']), 'count': e['count'], 'own': e['own']} for e in IE.get(f"fact:{f['id']}", [])]})
    cand = [dict(cref(c['id']), figures=figures(c['text'])) for c in public
            if c['label'] != 'analysis' and c.get('who') != 'audience' and c['id'] not in stat_cited and figures(c['text'])]
    numbers = dict(head, about='The figures of the media kit: every fact with use stat, with the figures it states, its wording (which keeps the '
                   "figure's scope: market, period, basis, comparison), status, credit lines, claims and things; then the public claims that state a "
                   'figure no stat fact cites yet, as candidates for the kit. Cite the claim ids, and quote the whole wording, never the figure alone.',
                   rule=rule(9), facts=facts, candidates=cand)

    # ---- differences ledger
    rows = []
    for x in kb['kits'].get('differences', []):
        docs = list(x.get('docs') or [])
        ids = list(x['event']) + docs + list(x['analysis'])
        pages = list(dict.fromkeys([k for c in docs for k in CL[c].get('src', []) if (sources[k].get('kind') or 'google') == 'google'] + list(x.get('pages') or [])))
        rows.append({'id': x['id'], 'title': bk.nt(x['title']), 'follow': bk.nt(x['follow']),
                     'event': [cref(c) for c in x['event']], 'docs': [cref(c) for c in docs],
                     'pages': [{'key': k, 'title': sources[k]['title'], 'url': sources[k]['url'], 'publisher': sources[k]['publisher'],
                                'checked': str(sources[k]['checked'])} for k in pages],
                     'analysis': [cref(c) for c in x['analysis']], 'topics': topics_of(ids), 'entities': things_of(ids)})
    in_row = defaultdict(set)
    for r in rows:
        for k in ('event', 'docs', 'analysis'):
            for y in r[k]: in_row[y['id']].add(r['id'])
    pairs = [{'type': r['type'], 'from': cref(c['id']), 'to': cref(r['to']), 'rows': sorted(in_row[c['id']] & in_row[r['to']])}
             for c in public for r in c.get('rel', []) if r['type'] in ('contradicts', 'updates') and r['to'] in CL]
    hedged = [cref(c['id']) for c in public if HEDGE.search(bk.nt(c['text']))]
    differences = dict(head, about="Where what was said or shown at the event differs from Google's documentation, and what to follow: the rows "
                       '(hand-written in 25-kits/differences.yaml, every claim checked by the build), then the claims linked by contradicts or updates and '
                       'the claims whose text says they are uncertain (both added by the build). Cite the claim ids; follow is the author\'s guidance.',
                       rule=rule(13), rows=rows, pairs=pairs, hedged=hedged)

    # ---- question bank
    answers = defaultdict(list)
    for c in public:
        for r in c.get('rel', []):
            if r['type'] == 'answers' and r['to'] in CL: answers[r['to']].append(c['id'])
    aq = []
    for c in public:
        if c.get('who') != 'audience': continue
        an = answers.get(c['id'], [])
        g = grade([CL[x] for x in an]) if an else None
        aq.append({'question': cref(c['id']), 'answers': [cref(x) for x in an], 'grade': g, 'grade_label': GRADES[g][0] if g else 'No answer recorded',
                   'topics': c['topics'], 'entities': things_of([c['id']] + an)})
    said = lambda c: c['label'] == 'docs' or (c['label'] in EVENT and c.get('who') != 'audience' and who_short(c, S, google, sources) == 'Google')
    rank = lambda cids: sorted(cids, key=lambda x: (-used[x], order[x]))
    things = []
    for x in EN['list']:
        doc = [c for c in x['claims'] if said(CL[c]) and (CL[c]['label'] == 'docs' or CL[c]['ver'] in ('confirmed', 'consistent'))]
        und = [c for c in x['claims'] if said(CL[c]) and CL[c]['label'] in EVENT and CL[c]['ver'] == 'undocumented']
        if not doc and not und: continue
        things.append({'id': x['id'], 'name': x['name'], 'kind': x['kind'], 'question': f"What did Google say about {x['name']}?",
                       'claims': len(x['claims']), 'card': f"entities/{x['id']}.md",
                       'documented': {'count': len(doc), 'top': [cref(c) for c in rank(doc)[:TOP_SAID]]},
                       'event_only': {'count': len(und), 'top': [cref(c) for c in rank(und)[:TOP_SAID]]}})
    questions = dict(head, about='Questions with their answers: the audience questions asked at the event with the answers given and how far Google\'s '
                     "documentation backs them, and for each thing the event talked about, what Google said about it (its documentation, and Google's "
                     f'words at the event): documented first, then what was only said at the event, up to {TOP_SAID} claims each, those the kits rest on '
                     "first. An audience question is a question, not Google's position; cite the answer's claim ids. card: the thing's card in the agent pack.",
                     rules=[rule(5), rule(2)], audience=aq, things=things)
    return {'numbers': numbers, 'differences': differences, 'questions': questions}


def ledger_pages(data, bk, meta, links):
    """The Markdown pages of the ledgers: numbers (50-maps), differences (50-maps), dev_differences (the developer kit) and questions (the
    media kit). links: maps_claim, dev_claim, content_claim (claim record -> link to its session page) and content_card (thing id -> card)."""
    N, Df, Q = data['numbers'], data['differences'], data['questions']
    ver = f"Version {meta['version']} · data through {meta['through_txt']}."

    def line(c, link):
        w = f"{SAYS[c['label']]}, Day {c['day']} ({c['by']})" if c['label'] in EVENT else SAYS[c['label']] + (f", {c['by']}" if c['label'] in ('docs', 'press') else '')
        v = bk.VER[c['verification']] if c['verification'] not in ('source', 'n/a') else ''
        return f"- [`{c['id']}`]({link(c)}) {bk.md(w)}{', ' + v if v else ''}: {bk.md(c['text'])}"

    def gen(title, lead):
        return [GEN, f'# {title}', '', lead, '', ver, '']

    # ---- numbers registry (50-maps)
    sl = links['maps_claim']
    nm = gen('Numbers registry', f"Every figure of the media kit: the {len(N['facts'])} facts marked `use: stat` in `25-kits/content.yaml`, with the figures they "
             'state, their wording (which keeps the scope), status, claims, credit lines and things. Below them, the public claims that state a figure no stat fact cites yet.')
    if N['rule']: nm += [f"**The rule** (media kit wording rule 9): {bk.md(N['rule'])}", '']
    nm += ['## The registry', '', '| Fact | Figures | Wording, with its scope | Status | Claims | Credit | Things |', '| --- | --- | --- | --- | --- | --- | --- |']
    for f in N['facts']:
        cl = '; '.join(f"[`{c['id']}`]({sl(c)}) {LABEL_WORD[c['label']]}" + (f", {bk.VER[c['verification']]}" if c['verification'] not in ('source', 'n/a') else '')
                       for c in f['claims'])
        nm.append(f"| `{f['id']}` | {bk.cell(' · '.join(f['figures'])) or '*in words*'} | {bk.cell(f['statement'])} | {f['status_label']} | {cl} | "
                  f"{bk.cell('; '.join(f['credit']))} | {bk.cell(', '.join(e['name'] for e in f['entities'])) or '—'} |")
    nm += ['', '*Figures*: the numbers the wording states, with their units, ranges and qualifiers, as the build reads them; a figure written in words '
           '(doubled, one in six) shows as *in words*. Quote the whole wording, never the figure alone.', '',
           f"## Figures no stat fact cites ({len(N['candidates'])})", '',
           'Public slide, stage, documentation and press claims that state a figure (a number with a unit, or one written with thousands separators) and that '
           'no `use: stat` fact cites: candidates for the media kit. When one is worth quoting, add a fact with `use: stat` to `25-kits/content.yaml` '
           '(step 7 of `_system/PLAYBOOK.md`), with its scope. Audience questions and analysis claims are left out.', '']
    for d in sorted({c['day'] for c in N['candidates']}):
        nm += [f'### Day {d}', ''] + [line(c, sl) + f" **Figures:** {bk.md(' · '.join(c['figures']))}" for c in N['candidates'] if c['day'] == d] + ['']

    # ---- differences ledger (50-maps and the developer kit)
    def ledger(link, kit):
        lead = ("Where what was said or shown at Search Central Live differs from Google's documentation, and what to follow. "
                f"{len(Df['rows'])} differences, hand-written in `25-kits/differences.yaml` and checked by the build against the claims; below them, the claims "
                'the data links as contradicting or updating another claim and the claims that say they are uncertain, both added by the build.')
        out = gen('Differences ledger', lead + (' Read it before you build: a requirement rests on what Google documents.' if kit else ''))
        if Df['rule']: out += [f"**The rule** (media kit wording rule 13): {bk.md(Df['rule'])}", '']
        if Df['rows']:
            out += ['## At a glance', '', '| Row | Difference | What to follow |', '| --- | --- | --- |']
            out += [f"| [{r['id']}](#{anchor(r['id'] + ' ' + r['title'])}) | {bk.cell(r['title'])} | {bk.cell(r['follow'])} |" for r in Df['rows']]
            out += ['', '## The differences', '',
                    "Each row: what to follow, what was said or shown at the event, what Google's documentation says, and the author's analysis of the gap.", '']
        for r in Df['rows']:
            out += [f"### {r['id']} {bk.md(r['title'])}", '', f"**Follow:** {bk.md(r['follow'])}", '', '**At the event**', ''] + [line(c, link) for c in r['event']]
            out += ['', "**Google's documentation**", ''] + [line(c, link) for c in r['docs']]
            out += [f"- Google page: [{bk.md(p['title'])}]({p['url']}) ({bk.md(p['publisher'])}, checked {p['checked']})" for p in r['pages']]
            out += ['', "**The author's analysis**", ''] + [line(c, link) for c in r['analysis']] + ['']
            if r['entities']: out += ['Things: ' + ', '.join(bk.md(e['name']) for e in r['entities'][:8]) + '.', '']
        out += [f"## Claims linked as contradicting or updating ({len(Df['pairs'])})", '',
                'Set with `rel` on the later claim in `20-claims/`. A pair that no row above covers is usually two views at the event (Google and a community '
                "speaker, or two talks) or a later page of Google's documentation, not an event-against-documentation difference.", '']
        for p in Df['pairs']:
            out += [f"- `{p['from']['id']}` {p['type']} `{p['to']['id']}`" + (f" (row {', '.join(p['rows'])})" if p['rows'] else ''),
                    '  ' + line(p['from'], link), '  ' + line(p['to'], link)]
        out += ['', f"## Claims that say they are uncertain ({len(Df['hedged'])})", '',
                'Their text states the uncertainty: an unclear recording, an uncertain word, a best reading. Keep the hedge in your wording or leave the point '
                'out (media kit wording rule 10).', '']
        for d in sorted({c['day'] for c in Df['hedged']}):
            out += [f'### Day {d}', ''] + [line(c, link) for c in Df['hedged'] if c['day'] == d] + ['']
        return '\n'.join(out)

    # ---- question bank (media kit)
    ql = links['content_claim']
    qm = gen('Question bank', 'Questions with their answers, ready for a Q&A post, an FAQ or an AI agent: the audience questions asked at the event with the '
             "answers given and how far Google's documentation backs them, and for each thing the event talked about, what Google said about it.")
    qm += ["- An audience question is a question, not Google's position: only the answer can be credited to Google (media kit wording rule 5).",
           f"- *Documented* answers rest on Google's documentation or on event claims it confirms or supports. Answers marked *{STATUS['event-only'][0]}* "
           'are not in the documentation: present them as said at the event, never as documented policy.',
           '- Keep the claim ids in drafts and use the credit lines of the [media kit README](README.md#credit-lines) in the published text.', '',
           f"## Audience questions ({len(Q['audience'])})", '']
    for d in sorted({q['question']['day'] for q in Q['audience']}):
        qm += [f'### Day {d}', '']
        for q in [q for q in Q['audience'] if q['question']['day'] == d]:
            c = q['question']
            qm += [f"**[`{c['id']}`]({ql(c)})** · {bk.md(c['session'])} · Answer: {q['grade_label']}", '', f"**Question:** {bk.md(c['text'])}", '']
            qm += ([line(a, ql) for a in q['answers']] if q['answers'] else ['- No answer was recorded.']) + ['']
    qm += [f"## What did Google say about it? ({len(Q['things'])} things)", '',
           f"For each thing the event talked about: up to {TOP_SAID} documented claims and up to {TOP_SAID} claims said only at the event, Google's words only "
           '(community speakers and audience questions are left out), the claims the kits rest on first. Its card lists everything else.', '']
    for t in Q['things']:
        qm += [f"### {bk.md(t['question'])}", '',
               f"{t['claims']} claim{'s' * (t['claims'] != 1)} mention {bk.md(t['name'])}: {t['documented']['count']} documented, "
               f"{t['event_only']['count']} said at the event only. [Card]({links['content_card'](t['id'])}).", '']
        if t['documented']['top']: qm += ['**Documented**', ''] + [line(c, ql) for c in t['documented']['top']] + ['']
        if t['event_only']['top']: qm += [f"**{STATUS['event-only'][0]}, not in Google's documentation**", ''] + [line(c, ql) for c in t['event_only']['top']] + ['']
    return {'numbers': '\n'.join(nm), 'differences': ledger(links['maps_claim'], False), 'dev_differences': ledger(links['dev_claim'], True), 'questions': '\n'.join(qm)}
